version: '3'

services:
  api-arv:
    container_name: api-arv
    image: node:16.14.0-alpine
    working_dir: /usr/app/arv
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app/arv
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
    command: yarn start:dev
    networks:
      - arv
  tempo:
    image: grafana/tempo
    container_name: tempo
    volumes:
      - ./infra/tempo/tempo.yml:/etc/tempo.yml
      - ./data/tempo:/tmp/tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    ports:
      - 3200:3200
      - 4318:4318  # otlp http
    networks:
      - arv
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - './infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    networks:
      - arv

networks:
  arv:
    external: true
  # api-arv:
  #   image: joaoduarte10/api-arv:latest
  #   container_name: api-arv
  #   expose:
  #     - 3000
  #   environment:
  #     SETTINGS_RELOAD_TIME: ${SETTINGS_RELOAD_TIME}
  #     PORT: ${PORT}
  #     CONSOLE_LOG_ENABLE: ${CONSOLE_LOG_ENABLE}
  #     PGUSER: ${PGUSER}
  #     PGHOST: ${PGHOST}
  #     PGPASSWORD: ${PGPASSWORD}
  #     PGDATABASE: ${PGDATABASE}
  #     PGPORT: ${PGPORT}
  #     JWT_SECRETS: ${JWT_SECRETS}
  #     JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
  #     TZ: America/Sao_Paulo
  # nginx:
  #   build:
  #     context: nginx/
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./conf/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./letsencrypt:/etc/letsencrypt
  #     - ../front/build:/usr/share/nginx/html
  #   depends_on:
  #     - api-arv