version: '3'

services:
  tempo:
    image: grafana/tempo
    container_name: tempo
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yml
      - ../data/tempo:/tmp/tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    ports:
      - 3200:3200
      - 4318:4318  # otlp http
    networks:
      - arv
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - ../data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    networks:
      - arv

networks:
  arv:
    external: true