datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://192.168.0.124:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
  - name: Tempo
    type: tempo
    access: proxy
    isDefault: false
    orgId: 1
    version: 1
    url: redis://192.168.0.112:3200
    editable: true