{
 "title": "Logs of Loki",
 "tags": [ "Loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "level_filter", "label": "Level Filter", "query": "info" },
   { "name": "context_filter", "label": "Context Filter" },
   { "name": "referrer_filter", "label": "Referrer Filter" },
   { "name": "application", "label": "Application Name", "query": "grafana-loki" }
  ]
 },
 "panels": [
  {
   "title": "Counter Logger Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({application=\"$application\"} [$__range]))",
     "legendFormat": "Info"
    }
   ]
  },
  {
   "title": "Counter Logger Info",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({application=\"$application\", level=\"info\"} [$__range]))",
     "legendFormat": "Info"
    }
   ]
  },
  {
   "title": "Counter Logger Error",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({application=\"$application\", level=\"error\"} [$__range]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Counter Logger Warn",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({application=\"$application\", level=\"warn\"} [$__range]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Logger Query",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{application=\"$application\", level=\"$level_filter\"} |= `context` |= `$context_filter` |= `referrer` |= `$referrer_filter`",
     "legendFormat": "Info"
    }
   ]
  }
 ]
}