{
 "title": "Aplication Metrics",
 "description": "Métricas da aplicação, como consumo de recursos e requests.",
 "tags": [
  "backend",
  "prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application_name", "label": "ApplicationName", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_all_request_total" }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\"}[1m]))\n+\n  sum(rate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\"}[1m]))\n) / 2 / sum(rate(api_request_duration_milliseconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Errors %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( api_all_errors_total / api_all_request_total ) * 100"
    }
   ]
  },
  {
   "title": "Requests in Processing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_all_request_in_processing_total"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_process_cpu_usage_percentage"
    }
   ]
  },
  {
   "title": "Heap Used, Mb",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nodejs_process_memory_heap_used_bytes)/1048576"
    }
   ]
  },
  {
   "title": "Heap Used, Mb",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodejs_process_memory_heap_used_bytes / 1048576",
     "legendFormat": "Instance: {{instance}} - Job: {{job}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodejs_process_cpu_usage_percentage"
    }
   ]
  },
  {
   "title": "Total Request By Route and Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by(http_route, http_method) (rate(core_http_server_duration_count{http_route!=\"/\", http_route!=\"\", job=\"$application_name\"}[$__interval])) * 60, 1)",
     "legendFormat": "{{http_method}} - {{http_route}}"
    }
   ]
  },
  {
   "title": "Total Request By Route and Method And StatusCode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by(http_route, http_method, http_status_code) (rate(core_http_server_duration_count{http_route!=\"/\", http_route!=\"\", job=\"$application_name\"}[$__interval])) * 60, 1)",
     "legendFormat": "{{http_method}} - {{http_status_code}} -  {{http_route}}"
    }
   ]
  },
  {
   "title": "Request By Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by(http_status_code) (rate(core_http_server_duration_count{http_route!=\"/\", http_route!=\"\", job=\"$application_name\"}[$__interval])) * 60, 1)",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Requests By Methods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum by(http_method) (rate(core_http_server_duration_count{http_route!=\"/\", http_route!=\"\", job=\"$application_name\"}[$__interval])) * 60)",
     "legendFormat": "{{http_method}}"
    }
   ]
  },
  {
   "title": "Top 3 API calls (by path)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(topk(3, sum by(http_route) (rate(core_http_server_duration_count{http_route!=\"/\", http_route!=\"\", job=\"$application_name\"}[$__interval]))) * 60)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Top 3 API Error Calls ( 5XX, by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(core_http_server_duration_count{http_status_code=~\"^5..$\"}[1m])) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apdex Score: target 25ms, tolerated: 100ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  sum(irate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\"}[1m]))\n+\n  (sum(irate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\"}[1m]))/2)\n) / sum(irate(api_request_duration_milliseconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Request Duration (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"5\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 5ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"10\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 10ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"50\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 50ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"100\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 100ms (%)"
    }
   ]
  }
 ]
}